version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-message-manager
    restart: unless-stopped
    
    # Portas - apenas localhost para segurança
    ports:
      - "127.0.0.1:8000:8000"
    
    # Carregar variáveis do arquivo .env
    env_file:
      - .env
    
    # Variáveis de ambiente específicas do container
    environment:
      - HOST=0.0.0.0  # Dentro do container precisa ser 0.0.0.0
      - PORT=8000
    
    # Volumes para persistência
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
      - ./logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Configurações de segurança
    security_opt:
      - no-new-privileges:true
    
    # Limitar recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Rede interna
    networks:
      - whatsapp-network

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    
    depends_on:
      whatsapp-api:
        condition: service_healthy
    
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge 